# Generated by Django 3.0.7 on 2021-06-28 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20210616_1558'),
        ('accounts', '0002_auto_20210615_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='locations.Locations'),
        ),
    ]
