# Generated by Django 3.0.7 on 2021-06-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
