# Generated by Django 3.0.7 on 2021-06-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='temp_image',
            field=models.ImageField(blank=True, null=True, upload_to='temp_image/'),
        ),
    ]
