# Generated by Django 3.0.7 on 2021-06-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_tool_temp_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='temp_image',
            field=models.ImageField(blank=True, null=True, upload_to='too_image/'),
        ),
    ]
