# Generated by Django 3.0.7 on 2021-06-25 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_auto_20210625_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='temp_image',
        ),
    ]
