# Generated by Django 3.0.7 on 2021-06-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_tempimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
