# Generated by Django 3.0.7 on 2021-06-28 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20210616_1558'),
        ('tools', '0006_auto_20210628_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='current_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='locations.Locations'),
        ),
    ]
