# Generated by Django 3.0.7 on 2021-07-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_auto_20210628_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='date_created',
            field=models.DateTimeField(editable=False),
        ),
    ]
