# Generated by Django 3.0.7 on 2021-07-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0009_auto_20210715_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
